using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace Prepper.Models
{
    public class RecipeInstruction : BaseModel
    {
        // Unique identifier for the recipe instruction generated by the database
        [PrimaryKey("id", false)]
        public int Id { get; set; }

        // Timestamp of when the recipe instruction was created in the database
        [Column("created_at", ignoreOnInsert: true)]
        public DateTimeOffset CreatedAt { get; set; }

        // Foreign key to the associated recipe
        [Column("recipe_id")]
        public int RecipeId { get; set; }

        // Step number in the recipe
        [Column("step_number")]
        public int StepNumber { get; set; }

        // Instruction text for the recipe step
        [Column("instruction_text")]
        public string InstructionText { get; set; }

        // Parameterized constructor
        public RecipeInstruction(int id, DateTimeOffset createdAt, int recipeId, int stepNumber, string instructionText)
        {
            Id = id;
            CreatedAt = createdAt;
            RecipeId = recipeId;
            StepNumber = stepNumber;
            InstructionText = instructionText;
        }

        // Default constructor
        public RecipeInstruction() { }

        // Override ToString for better readability
        public override string ToString()
        {
            return $"Id: {Id}, RecipeId: {RecipeId}, StepNumber: {StepNumber}, InstructionText: {InstructionText}, Created at {CreatedAt}";
        }

    }
}
